services:
  app:
    build: .
    volumes: ['.:/app']
    ports: ['3000:3000']
    depends_on: ['redis','postgres']
  redis:
    image: redis:alpine
    restart: unless-stopped
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: maindb
    volumes: ['pgdata:/var/lib/postgresql/data']
    ports: ['5432:5432']
volumes:
  pgdata: