services:
  app:
    build: .
    ports:
      - "3000:3000"  # для прямого доступа снаружи
    expose:
      - "3000"       # для nginx
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data   # подключаем volume для сохранения данных Redis

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  redis-data:
